[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npm run build -w backend"

[deploy]
startCommand = "npm run start -w backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
